server:
  address: 0.0.0.0
  port: 8086

spring:
  application:
  mvc:
    async:
      request-timeout: 600000
  main:
    allow-bean-definition-overriding: true
  data:
    neo4j:
      username: neo4j
      password: secret
      uri: bolt://127.0.0.1:7687

management:
  endpoints:
    web:
      exposure:
        exclude: shutdown
        include: '*'