server:
  address: 0.0.0.0
  port: 8085

spring:
  application:
  mvc:
    async:
      request-timeout: 600000
  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        exclude: shutdown
        include: '*'