server:
  address: 0.0.0.0
  port: 8086

spring:
  application:
  mvc:
    async:
      request-timeout: 600000
  main:
    allow-bean-definition-overriding: true
  data:
    arangodb:
      database: pnl-service3
      user: root
      password: secret
      hosts: 127.0.0.1:8529

management:
  endpoints:
    web:
      exposure:
        exclude: shutdown
        include: '*'